// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using Hashnode;
//
//    var hashnodeViewModel = HashnodeViewModel.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace Hashnode
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class HashnodeViewModel
    {
        [JsonPropertyName("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonPropertyName("publication")]
        public DataPublication Publication { get; set; }
    }

    public partial class DataPublication
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("metaTags")]
        public object MetaTags { get; set; }

        [JsonPropertyName("title")]
        public string Title { get; set; }

        [JsonPropertyName("descriptionSEO")]
        public object DescriptionSeo { get; set; }

        [JsonPropertyName("about")]
        public object About { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }

        [JsonPropertyName("canonicalURL")]
        public Uri CanonicalUrl { get; set; }

        [JsonPropertyName("author")]
        public PublicationAuthor Author { get; set; }

        [JsonPropertyName("seriesList")]
        public SeriesList SeriesList { get; set; }

        [JsonPropertyName("posts")]
        public Posts Posts { get; set; }
    }

    public partial class PublicationAuthor
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("username")]
        public string Username { get; set; }
    }

    public partial class Posts
    {
        [JsonPropertyName("pageInfo")]
        public PageInfo PageInfo { get; set; }

        [JsonPropertyName("totalDocuments")]
        public long TotalDocuments { get; set; }

        [JsonPropertyName("edges")]
        public List<Edge> Edges { get; set; }
    }

    public partial class Edge
    {
        [JsonPropertyName("cursor")]
        public string Cursor { get; set; }

        [JsonPropertyName("node")]
        public Node Node { get; set; }
    }

    public partial class Node
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("publication")]
        public NodePublication Publication { get; set; }

        [JsonPropertyName("bannerImage")]
        public ErImage BannerImage { get; set; }

        [JsonPropertyName("coverImage")]
        public ErImage CoverImage { get; set; }

        [JsonPropertyName("brief")]
        public string Brief { get; set; }

        [JsonPropertyName("readTimeInMinutes")]
        public long ReadTimeInMinutes { get; set; }

        [JsonPropertyName("publishedAt")]
        public DateTimeOffset PublishedAt { get; set; }

        [JsonPropertyName("featuredAt")]
        public object FeaturedAt { get; set; }

        [JsonPropertyName("updatedAt")]
        public DateTimeOffset UpdatedAt { get; set; }

        [JsonPropertyName("seo")]
        public Seo Seo { get; set; }

        [JsonPropertyName("views")]
        public long Views { get; set; }

        [JsonPropertyName("series")]
        public object Series { get; set; }

        [JsonPropertyName("slug")]
        public string Slug { get; set; }

        [JsonPropertyName("featured")]
        public bool Featured { get; set; }

        [JsonPropertyName("features")]
        public Features Features { get; set; }

        [JsonPropertyName("content")]
        public Content Content { get; set; }

        [JsonPropertyName("ogMetaData")]
        public OgMetaData OgMetaData { get; set; }

        [JsonPropertyName("url")]
        public Uri Url { get; set; }

        [JsonPropertyName("subtitle")]
        public string Subtitle { get; set; }

        [JsonPropertyName("author")]
        public NodeAuthor Author { get; set; }

        [JsonPropertyName("tags")]
        public List<Tag> Tags { get; set; }

        [JsonPropertyName("canonicalUrl")]
        public object CanonicalUrl { get; set; }
    }

    public partial class NodeAuthor
    {
        [JsonPropertyName("username")]
        public string Username { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }
    }

    public partial class ErImage
    {
        [JsonPropertyName("url")]
        public Uri Url { get; set; }
    }

    public partial class Content
    {
        [JsonPropertyName("markdown")]
        public string Markdown { get; set; }

        [JsonPropertyName("html")]
        public string Html { get; set; }
    }

    public partial class Features
    {
        [JsonPropertyName("tableOfContents")]
        public TableOfContents TableOfContents { get; set; }
    }

    public partial class TableOfContents
    {
        [JsonPropertyName("isEnabled")]
        public bool IsEnabled { get; set; }

        [JsonPropertyName("items")]
        public List<Item> Items { get; set; }
    }

    public partial class Item
    {
        [JsonPropertyName("id")]
        public string? Id { get; set; }

        [JsonPropertyName("level")]
        public long Level { get; set; }

        [JsonPropertyName("slug")]
        public string Slug { get; set; }

        [JsonPropertyName("title")]
        public string Title { get; set; }

        [JsonPropertyName("parentId")]
        public object ParentId { get; set; }
    }

    public partial class OgMetaData
    {
        [JsonPropertyName("image")]
        public Uri Image { get; set; }
    }

    public partial class NodePublication
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }
    }

    public partial class Seo
    {
        [JsonPropertyName("title")]
        public string Title { get; set; }

        [JsonPropertyName("description")]
        public string Description { get; set; }
    }

    public partial class Tag
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("slug")]
        public string Slug { get; set; }

        [JsonPropertyName("logo")]
        public Uri Logo { get; set; }

        [JsonPropertyName("tagline")]
        public object Tagline { get; set; }
    }

    public partial class PageInfo
    {
        [JsonPropertyName("endCursor")]
        public string EndCursor { get; set; }

        [JsonPropertyName("hasNextPage")]
        public bool HasNextPage { get; set; }
    }

    public partial class SeriesList
    {
        [JsonPropertyName("totalDocuments")]
        public long TotalDocuments { get; set; }

        [JsonPropertyName("edges")]
        public List<object> Edges { get; set; }
    }

    public partial class HashnodeViewModel
    {
        public static HashnodeViewModel FromJson(string json) => JsonSerializer.Deserialize<HashnodeViewModel>(json, Hashnode.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this HashnodeViewModel self) => JsonSerializer.Serialize(self, Hashnode.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
            get => _dateTimeStyles;
            set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
            get => _dateTimeFormat ?? string.Empty;
            set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
            get => _culture ?? CultureInfo.CurrentCulture;
            set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            string text;


            if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                    || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
            {
                value = value.ToUniversalTime();
            }

            text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

            writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? dateText = reader.GetString();

            if (string.IsNullOrEmpty(dateText) == false)
            {
                if (!string.IsNullOrEmpty(_dateTimeFormat))
                {
                    return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                }
                else
                {
                    return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                }
            }
            else
            {
                return default(DateTimeOffset);
            }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
