FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Electra.Identity.Server/Electra.Identity.Server/Electra.Identity.Server.csproj", "Electra.Identity.Server/Electra.Identity.Server/"]
COPY ["Electra.Identity.Server/Electra.Identity.Server.Client/Electra.Identity.Server.Client.csproj", "Electra.Identity.Server/Electra.Identity.Server.Client/"]
RUN dotnet restore "Electra.Identity.Server/Electra.Identity.Server/Electra.Identity.Server.csproj"
COPY . .
WORKDIR "/src/Electra.Identity.Server/Electra.Identity.Server"
RUN dotnet build "./Electra.Identity.Server.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Electra.Identity.Server.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Electra.Identity.Server.dll"]
